### ISSUE TITLE
CenterImgSrchCoords fails when shades of variation > 0

### ISSUE THREAD

**Issue by Melikoth** [Pulover/PuloversMacroCreator#40]
When shades of variation is set to 0, the CenterImgSrchCoords function will correctly center on the image, however if it is increased to 1 or higher then the coordinates always return the upper left corner of the image.

This code will work as expected:

```
ImageSearch, FoundX, FoundY, 0, 0, 1920, 1080, C:\CHB\image.png
CenterImgSrchCoords("C:\CHB\image.png", FoundX, FoundY)
If ErrorLevel = 0
    Click, %FoundX%, %FoundY% Left, 1
```

But this clicks the upper left corner:

```
ImageSearch, FoundX, FoundY, 0, 0, 1920, 1080, *64 C:\CHB\image.png
CenterImgSrchCoords("*64 C:\CHB\image.png", FoundX, FoundY)
If ErrorLevel = 0
    Click, %FoundX%, %FoundY% Left, 1
```

**Comment by goldmonkey163com** [comment]
I found the same problem with you. It can temporarily solved by exporting to ahk file and  removing "*64" in "CenterImgSrchCoords("*64 C:\CHB\image.png", FoundX, FoundY)"

**Comment by nw2372** [comment]
This also happens when selecting a transparent color:
"CenterImgSrchCoords("*Trans0xFFFFFF C:\Users\David\AppData\Roaming\MacroCreator\Screenshots\Screen_20180108155624.png", FoundX, FoundY)"
It is not fixed in the current version.

**Comment by Sappurit** [comment]
Yes, ton of bugs. I switch to Notepad already.
The code is wrong. Look when convert to AHK:

```
Macro1:
Loop
{
    CoordMode, Pixel, Window
    ImageSearch, FoundX, FoundY, 0, 0, 1920, 1080, *69 D:\download\PuloversMacroCreator-Portable\MacroCreatorPortable\x86\MacroCreator\Screenshots\Screen_20180812200820.png
    CenterImgSrchCoords("*69 D:\download\PuloversMacroCreator-Portable\MacroCreatorPortable\x86\MacroCreator\Screenshots\Screen_20180812200820.png", FoundX, FoundY)
}
Until ErrorLevel = 0
If ErrorLevel = 0
{
}
Return


CenterImgSrchCoords(File, ByRef CoordX, ByRef CoordY)
{
	static LoadedPic
	LastEL := ErrorLevel
	Gui, Pict:Add, Pic, vLoadedPic, %File%
	GuiControlGet, LoadedPic, Pict:Pos
	Gui, Pict:Destroy
	CoordX += LoadedPicW // 2
	CoordY += LoadedPicH // 2
	ErrorLevel := LastEL
}


```

**Comment by Sappurit** [comment]
Create my own function:

```
ImageSearchMouseCenter(ByRef xMouse, ByRef yMouse, File)
{
	LastErrorLevel := ErrorLevel

	static LoadedPic
	Gui -DPIScale
	Gui, Add, Picture, vLoadedPic, %File%
	GuiControlGet, LoadedPic, Pos
	Gui, Destroy
	xMouse += LoadedPicW // 2
	yMouse += LoadedPicH // 2

	ErrorLevel := LastErrorLevel
}
```
and use as

```
        Loop
        {
            CoordMode, Pixel, Window
            ImageSearch, x, y, 0, 0, 1920, 1080, *120 Sail_Img_1.png
            ImageSearchMouseCenter(x, y, "Sail_Img_1.png")
            Sleep, 200
        }
        Until ErrorLevel = 0
        If ErrorLevel = 0
        {
            MsgBox, %x% %y%
        }

return
```

**Comment by Pulover** [comment]
ImageSearch options are prefixed to the file name in this command I forgot to trim them. Will be fixed in the next release.

**Comment by Pulover** [comment]
Fixed in v5.1.2.
